### PR TITLE
Fix/370 cursor input

### LINKED ISSUE #370: Review how input handle changes and cursor position (when validating they are numbers)
Make another round in modeling inputs for a specific path in the db with a generic update handler. 
Should support setting prop for value again

If user edits numeric input in the middle position the cursor position is changed to the end

### PR DESCRIPTION
**Pull request by solsarratea**
Closes #370

### CODE REVIEW

File: src/planwise/client/components/common2.cljs [hunk 1]
```diff
@@ -29,3 +31,17 @@
   (accountant/navigate! route)
   [ui/fixed-width (nav-params)
    [:p "Loading..."]])
+
+(defn text-field
+  [{:keys [label value] :as props}]
+  (let [focus  (r/atom false)
+        id     (str (random-uuid))]
+    (fn [{:keys [label value] :as props}]
+      [:div.mdc-text-field.mdc-text-field--upgraded {:class (when @focus "mdc-text-field--focused")}
```
Comment (ggiraldez) [inline src/planwise/client/components/common2.cljs]: Is the `--upgraded` class necessary? It was my understanding that it only means the component has been modified/hooked by javascript code.

File: src/planwise/client/components/common2.cljs [hunk 2]
```diff
@@ -29,3 +31,17 @@
...
+       [:input.mdc-text-field__input (merge props {:id id
```
Comment (ggiraldez) [inline src/planwise/client/components/common2.cljs]: You may want to `(dissoc props :label)` before passing it to the `:input` component.

**Comment by ggiraldez** [comment]
Wait for the merge of #392 and then rebase to `master`.
