### PR TITLE
Try to fix isolated segments.

### LINKED ISSUE #12: Address isolated components in the topology graph
There are some instance in the OSM data where some ways are completely isolated from the road network (eg. a pedestrian pathway; see Lat -1.2595 Lon 36.8446). If a facility is located near one, the algorithm will choose a node in the isolated component for the origin of the isochrone and will yield an incorrect catchment area. There might be other places where there are disconnections due to human error when entering the map data as well.

Either remove the isolated components entirely or find a way to detect and correct these situations.

### PR DESCRIPTION
**Pull request by ggiraldez**
When importing the OSM data, as a post-processing step try to connect
the isolated segments back to the main network. The threshold used for
finding a nearby node is 5km which is the same as used when considering
a facility is too far during importing.

Closes #12

### CODE REVIEW

File: scripts/import-osm [hunk 1]
```diff
@@ -54,6 +59,7 @@ ${OSM2PGROUTING} -f /tmp/$COUNTRY.osm -c $(dirname "${BASH_SOURCE}")/mapconfig.x
 echo "Populating ways_nodes table"
 psql -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST << SQL_SCRIPT
 SELECT populate_ways_nodes();
+SELECT connect_isolated_segments(5000);
```
Comment (spalladino) [inline scripts/import-osm]: Is the function idempotent? If so, it might make sense to add it as a migration, so we don't forget running it manually on dev, stg or prod.

File: resources/planwise/plpgsql/fix-isolated.sql [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+  fixed_segments INTEGER;
+  segment_fixed BOOLEAN;
+BEGIN
+  RAISE NOTICE 'Trying to fix up isolated segments';
+
+  isolated := 0;
+  created_ways := 0;
+  fixed_segments := 0;
+
+  FOR segment IN SELECT w.*, a.the_geom AS source_geom, b.the_geom AS target_geom FROM ways w, ways_vertices_pgr a, ways_vertices_pgr b WHERE w.source = a.id AND a.cnt = 1 AND w.target = b.id AND b.cnt = 1 LOOP
```
Comment (spalladino) [inline resources/planwise/plpgsql/fix-isolated.sql]: This will only address isolated segments. Do we know if there are isolated components?

File: resources/planwise/plpgsql/fix-isolated.sql [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+           WHERE id NOT IN (segment.source, segment.target)
+           ORDER by w.the_geom <-> segment.target_geom
+           LIMIT 1
+           INTO closest_to_target;
+    IF ST_Distance(segment.target_geom::geography, closest_to_target.the_geom::geography) < threshold THEN
+       new_way_gid := insert_way(segment.class_id, segment.maxspeed_forward, segment.target, closest_to_target.id);
+       created_ways := created_ways + 1;
+       segment_fixed := TRUE;
+    END IF;
+
```
Comment (spalladino) [inline resources/planwise/plpgsql/fix-isolated.sql]: Instead of trying with `closest_to_source` first and then falling back to `closest_to_target`, I'd suggest querying both of them, and then taking the closest of the two (as long as it's within the threshold).

File: resources/planwise/plpgsql/fix-isolated.sql [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+  geom := ST_MakeLine(ARRAY[source_node.the_geom, target_node.the_geom]);
+  length_m := ST_Length(geom::geography);
+
+  INSERT INTO ways
+         (class_id, length, length_m, source, target, x1, y1, x2, y2,
+          cost, one_way, maxspeed_forward, the_geom)
+         VALUES (class_id, ST_Length(geom), length_m, source, target,
+                 ST_X(source_node.the_geom), ST_Y(source_node.the_geom),
+                 ST_X(target_node.the_geom), ST_Y(target_node.the_geom),
+                 ST_Length(geom), 0, speed, geom)
```
Comment (spalladino) [inline resources/planwise/plpgsql/fix-isolated.sql]: If we run this function independently, then it'd make sense to consider the traffic factor when inserting the cost here.

File: scripts/import-osm (hunk 1 above)
Comment (ggiraldez) [inline scripts/import-osm]: I don't like mixing this with migrations. If we add more countries we would run the function again to address isolated segments from the new data. It's also not truly idempotent: after run, we cannot change the threshold.

File: resources/planwise/plpgsql/fix-isolated.sql (hunk 4 above)
Comment (ggiraldez) [inline resources/planwise/plpgsql/fix-isolated.sql]: For that we'd need to pass the traffic factor to this function as well, which I don't like. Leaving the `cost_s` as NULL will trigger errors when importing new facilities that reach the new ways, which may be enough of a reminder. Would you negotiate printing an alert reminding you to re-run `apply_traffic_factor` after this function is executed?

Comment (spalladino) [inline resources/planwise/plpgsql/fix-isolated.sql]: Worksforme!

File: resources/planwise/plpgsql/fix-isolated.sql (hunk 2 above)
Comment (ggiraldez) [inline resources/planwise/plpgsql/fix-isolated.sql]: There's not an easy way of finding out. And it can't be done automatically anyway. Think of roads on islands for example https://www.google.com.ar/maps/@-0.4662908,34.0303715,13.38z?hl=en

File: scripts/import-osm (hunk 1 above)
Comment (spalladino) [inline scripts/import-osm]: Ok, but we'll need to keep in mind to run this on all envs on the next release

File: resources/planwise/plpgsql/fix-isolated.sql (hunk 2 above)
Comment (spalladino) [inline resources/planwise/plpgsql/fix-isolated.sql]: I've just checked and `cnt` in my `ways_vertices_pgr table` is NULL for all rows. Isn't `pgr_analyzeGraph` needed to be run beforehand?

File: resources/planwise/plpgsql/fix-isolated.sql (hunk 3 above)
Comment (ggiraldez) [inline resources/planwise/plpgsql/fix-isolated.sql]: The code does attempt to connect both.

File: resources/planwise/plpgsql/fix-isolated.sql (hunk 2 above)
Comment (ggiraldez) [inline resources/planwise/plpgsql/fix-isolated.sql]: AFAIK, this is done by `osm2pgrouting`

Comment (ggiraldez) [inline resources/planwise/plpgsql/fix-isolated.sql]: No, it's not. But we do it now in `import-osm` before running the connect function.

File: resources/planwise/plpgsql/fix-isolated.sql (hunk 4 above)
Comment (ggiraldez) [inline resources/planwise/plpgsql/fix-isolated.sql]: Done.
